### PR TITLE
Remove minify to make the code debuggable

### PR DESCRIPTION
**Pull request by TrySound**
I just got an error somewhere deeply inside of this library and cannot
figure out what's going on because the code here is minified and chrome
is not able to apply formatter.

Would be good to publish the new patch soon so I could find the problem
in my code.

### CODE REVIEW

**Comment by ibgreen** [comment]
@TrySound We don't minify before we publish. We do transpile the code though. We offer three different distributions with varying degrees of transpilation. 

* https://unpkg.com/viewport-mercator-project@5.2.0/dist/es6/index.js
* https://unpkg.com/viewport-mercator-project@5.2.0/dist/esm/index.js
* https://unpkg.com/viewport-mercator-project@5.2.0/dist/es5/index.js

The es6 distribution would be the best for debugging, the es5 distribution is intended for old browsers.

The dists have entry points listed in `package.json`, but the `es6` key is not recognized directly by bundlers and must be selected manually. In webpack that can be done via the `resolve.mainFields` setting, not sure about rollup etc.

Hope that helps a little.

**Comment by TrySound** [comment]
Here's esm pretty printed (by chrome) code. And it's not debuggable.

image

**Comment by ibgreen** [comment]
You are right. I had removed `babel-minify` from the major frameworks but apparently still present here in the smaller frameworks.

Always experimenting with ways to reduce the bundle size...

**Comment by TrySound** [comment]
Would be good to publish a patch release with this change

**Comment by ibgreen** [comment]
@TrySound Just published `5.3.0-alpha.2`, let me know how it goes

**Pull request merged**
